// <auto-generated />
using System;
using CLI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CLI.Migrations.User
{
    [DbContext(typeof(UserContext))]
    [Migration("20230718134750_AddUserContext")]
    partial class AddUserContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("CLI.Models.GenerationFlow", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Flow")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "Date");

                    b.ToTable("GenerationFlows");
                });

            modelBuilder.Entity("CLI.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("CLI.Models.Subscriber", b =>
                {
                    b.HasBaseType("CLI.Models.User");

                    b.Property<DateTime>("Expiration")
                        .HasColumnType("datetime2");

                    b.HasDiscriminator().HasValue("Subscriber");
                });
#pragma warning restore 612, 618
        }
    }
}
