// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StableDraw.Domain.Data.Task;

#nullable disable

namespace StableDraw.Domain.Data.Task.Migrations
{
    [DbContext(typeof(TaskContext))]
    partial class TaskContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("StableDraw.Core.Models.Generation", b =>
                {
                    b.Property<Guid>("Oid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Oid");

                    b.HasIndex("TaskId");

                    b.ToTable("Generations");
                });

            modelBuilder.Entity("StableDraw.Core.Models.Result", b =>
                {
                    b.Property<Guid>("Oid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GenerationId")
                        .HasColumnType("TEXT");

                    b.HasKey("Oid");

                    b.HasIndex("GenerationId")
                        .IsUnique();

                    b.ToTable("Results");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Result");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("StableDraw.Core.Models.Task", b =>
                {
                    b.Property<Guid>("Oid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Oid");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("StableDraw.Core.Models.CaptionResult", b =>
                {
                    b.HasBaseType("StableDraw.Core.Models.Result");

                    b.Property<string>("Property")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("Results", t =>
                        {
                            t.Property("Property")
                                .HasColumnName("CaptionResult_Property");
                        });

                    b.HasDiscriminator().HasValue("CaptionResult");
                });

            modelBuilder.Entity("StableDraw.Core.Models.ImageResult", b =>
                {
                    b.HasBaseType("StableDraw.Core.Models.Result");

                    b.Property<string>("Property")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("Results", t =>
                        {
                            t.Property("Property")
                                .HasColumnName("ImageResult_Property");
                        });

                    b.HasDiscriminator().HasValue("ImageResult");
                });

            modelBuilder.Entity("StableDraw.Core.Models.ParamsResult", b =>
                {
                    b.HasBaseType("StableDraw.Core.Models.Result");

                    b.Property<string>("Property")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("ParamsResult");
                });

            modelBuilder.Entity("StableDraw.Core.Models.Generation", b =>
                {
                    b.HasOne("StableDraw.Core.Models.Task", "Task")
                        .WithMany("Generations")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("StableDraw.Core.Models.Result", b =>
                {
                    b.HasOne("StableDraw.Core.Models.Generation", null)
                        .WithOne("Result")
                        .HasForeignKey("StableDraw.Core.Models.Result", "GenerationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StableDraw.Core.Models.Generation", b =>
                {
                    b.Navigation("Result")
                        .IsRequired();
                });

            modelBuilder.Entity("StableDraw.Core.Models.Task", b =>
                {
                    b.Navigation("Generations");
                });
#pragma warning restore 612, 618
        }
    }
}
