version: "3.7"


services:
  rabbitmq:
    image: rabbitmq:3-management-delayed_message_exchange
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672

  minio:
    image: minio/minio:latest
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    # expose:
    # - "9000"
    # - "9001"
    restart: always   
    environment:
      MINIO_ROOT_USER: stabledraw
      MINIO_ROOT_PASSWORD: minio123
      # MINIO_SERVER_URL: https://stabledraw.com
    volumes:
      - minio-storage:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - minio-local

  # nginx:
  #   image: nginx:1.19.2-alpine
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #     - ./certificate/www.stabledraw.com.crt:/etc/nginx/www.stabledraw.com/www.stabledraw.com.crt
  #     - ./certificate/www.stabledraw.com.key:/etc/nginx/www.stabledraw.com/www.stabledraw.com.key
  #     - ./certificate/ca.crt:/etc/nginx/www.stabledraw.com/ca.crt

  #     # - nginx/nginx.conf
  #     # - C:\\StableDrawWeb\\manifestos\\nginx\\nginx.conf
  #   ports:
  #     - mode: host
  #       protocol: tcp
  #       published: 80
  #       target: 80
  #   depends_on:
  #     - minio      
  #   networks:
  #     - minio-local
  # sagas:
  #   image: sagasbackend
  #   build: 
  #     context: ..
  #     dockerfile: StableDraw.SagasService/Dockerfile
  #   ports:
  #     - "5100:80"

  # minioService:
  #   image: miniobackend
  #   build:
  #     context: ..
  #     dockerfile: StableDraw.MinIOService/Dockerfile
  #   ports:
  #     - "5101:80"


  # db:
  #   image: postgres
  #   container_name: sagas_pgdb
  #   restart: always
  #   ports:
  #     - "54320:5432"
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: 1234
  #   volumes:
  #     - local_pgdata:/var/lib/postgresql/data
  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin4_container
  #   restart: always
  #   ports:
  #     - "5050:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@email.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   volumes:
  #     - pgadmin-data:/var/lib/pgadmin

# networks:
#   minio-local:
#     driver: bridge

volumes:
  minio-storage:
  # local_pgdata:
  # pgadmin-data: 