version: "3.7"
services:
  rabbitmq:
    image: rabbitmq:3-management-delayed_message_exchange
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672

  minio:
    image: minio/minio:latest
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: always
    environment:
      MINIO_ROOT_USER: stabledraw
      MINIO_ROOT_PASSWORD: minio123
      MINIO_SERVER_URL: http://stabledraw.com:9000
    volumes:
      - minio-storage:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
  
  # sagas:
  #   image: sagasbackend
  #   build: 
  #     context: ..
  #     dockerfile: StableDraw.SagasService/Dockerfile
  #   ports:
  #     - "5100:80"

  # minioService:
  #   image: miniobackend
  #   build:
  #     context: ..
  #     dockerfile: StableDraw.MinIOService/Dockerfile
  #   ports:
  #     - "5101:80"


  # db:
  #   image: postgres
  #   container_name: sagas_pgdb
  #   restart: always
  #   ports:
  #     - "54320:5432"
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: 1234
  #   volumes:
  #     - local_pgdata:/var/lib/postgresql/data
  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin4_container
  #   restart: always
  #   ports:
  #     - "5050:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@email.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   volumes:
  #     - pgadmin-data:/var/lib/pgadmin

volumes:
  minio-storage:
  # local_pgdata:
  # pgadmin-data: 