version: "3.7"


services:
  rabbitmq:
    image: rabbitmq:3-management-delayed_message_exchange
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672

  nginx:
    image: nginx
    ports:
      - "8443:8443"
      - "9000:9000"
      # - "43301:43301"
      # - "8080:8080"
    environment:
      - NGINX_HOST=www.stabledraw.com
      - STABLE_KITE_HOST=stablekite.ru
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf      
      - ./certificate/stabledraw/www.stabledraw.com.pem:/etc/nginx/www.stabledraw.com/www.stabledraw.com.pem
      - ./certificate/stabledraw/www.stabledraw.com.key:/etc/nginx/www.stabledraw.com/www.stabledraw.com.key
      - ./certificate/stabledraw/ca.pem:/etc/nginx/www.stabledraw.com/ca.pem
      - ./certificate/stablekite/www.stablekite.ru.crt:/etc/nginx/www.stablekite.ru/www.stablekite.ru.crt
      - ./certificate/stablekite/www.stablekite.ru.csr:/etc/nginx/www.stablekite.ru/www.stablekite.ru.csr
    depends_on:
      - minio
      # - wordpress
    restart: always

  wordpress:
    container_name: wordpress
    image: wordpress:php8.2-apache
    restart: always
    depends_on:
      - mariadb
    # ports:
    #   - 8080:85
    environment:
        WORDPRESS_DB_HOST: mariadb
        WORDPRESS_DB_USER: wbStableKite
        WORDPRESS_DB_PASSWORD: Robolightning_1862
        WORDPRESS_DB_NAME: dbStableKite
        WORDPRESS_CONFIG_EXTRA: |
          define( 'WP_HOME', 'http://www.stablekite.ru' );
          define( 'WP_SITEURL', 'http://www.stablekite.ru' );
    volumes:        
        - wordpress_data:/var/www/html

  mariadb:
    container_name: mariadb
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
        MYSQL_DATABASE: dbStableKite
        MYSQL_USER: wbStableKite
        MYSQL_PASSWORD: Robolightning_1862
        MYSQL_ROOT_PASSWORD: Robolightning_18621
    volumes:
        - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    volumes:
      - ./config/phpmyadmin.ini:/usr/local/etc/php/conf.d/phpmyadmin.ini
    environment:
      PMA_HOST: "mysql"
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: Robolightning_18621
    ports:
      - '8082:80'
    links:
      - mariadb:mariadb

  minio:
    image: minio/minio:latest
    container_name: minio
    command: server --console-address ":9001" /data/
    ports:
      - 9000
      - 9001
    # expose:
    # - "9000"
    # - "9001"
    restart: always   
    environment:
      MINIO_ROOT_USER: stabledraw
      MINIO_ROOT_PASSWORD: minio123
      MINIO_REGION_NAME: us-east-1
      MINIO_BROWSER_REDIRECT_URL: https://www.stabledraw.com
      MINIO_PROMETHEUS_AUTH_TYPE: "public" 
      # MINIO_SERVER_URL: https://stabledraw.com
    volumes:
      - minio-storage:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3    

volumes:
  minio-storage:
  db_data:
  wordpress_data:
    
  # nginx:
  #   image: nginx:1.19.2-alpine
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #     - ./certificate/www.stabledraw.com.crt:/etc/nginx/www.stabledraw.com/www.stabledraw.com.crt
  #     - ./certificate/www.stabledraw.com.key:/etc/nginx/www.stabledraw.com/www.stabledraw.com.key
  #     - ./certificate/ca.crt:/etc/nginx/www.stabledraw.com/ca.crt

  #     # - nginx/nginx.conf
  #     # - C:\\StableDrawWeb\\manifestos\\nginx\\nginx.conf
  #   ports:
  #     - mode: host
  #       protocol: tcp
  #       published: 80
  #       target: 80
  #   depends_on:
  #     - minio      
  #   networks:
  #     - minio-local
  # sagas:
  #   image: sagasbackend
  #   build: 
  #     context: ..
  #     dockerfile: StableDraw.SagasService/Dockerfile
  #   ports:
  #     - "5100:80"

  # minioService:
  #   image: miniobackend
  #   build:
  #     context: ..
  #     dockerfile: StableDraw.MinIOService/Dockerfile
  #   ports:
  #     - "5101:80"


  # db:
  #   image: postgres
  #   container_name: sagas_pgdb
  #   restart: always
  #   ports:
  #     - "54320:5432"
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: 1234
  #   volumes:
  #     - local_pgdata:/var/lib/postgresql/data
  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin4_container
  #   restart: always
  #   ports:
  #     - "5050:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@email.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   volumes:
  #     - pgadmin-data:/var/lib/pgadmin

# networks:
#   minio-local:
#     driver: bridge


  # local_pgdata:
  # pgadmin-data: 